### ISSUE TITLE
안녕하세요 트리관련해서 질문올립니다.

### ISSUE THREAD

**Issue by goodsosbva** [onlybooks/algorithm-interview#102]
`class TreeNode:
    def __init__(self, x):
        self.val = x
        self.left = None
        self.right = None

class Solution:
    def mergeTrees(self, t1: TreeNode, t2: TreeNode) -> TreeNode:
        if t1 and t2:
            node = TreeNode(t1.val + t2.val)
            node.left = self.mergeTrees(t1.left, t2.left)
            node.right = self.mergeTrees(t1.right, t2.right)

            return node
        else:
            return t1 or t2

root1 = [1, 3, 2, 5]
root2 = [2, 1, 3, 0, 4, 0, 7]
sol = Solution()
check = sol.mergeTrees(root1, root2)
print(check)
# 트리노드를 어떻게 입력해야 할까요?`

이런 개인 ide 환경에서 실행보려고하면
Traceback (most recent call last):
  File "C:/Users/hs/PycharmProjects/pythonProject1/CodingInterView/617.py", line 27, in <module>
    check = sol.mergeTrees(root1, root2)
  File "C:/Users/hs/PycharmProjects/pythonProject1/CodingInterView/617.py", line 15, in mergeTrees
    node = TreeNode(t1.val + t2.val)
AttributeError: 'list' object has no attribute 'val'

이런 문제가 나오는데 어떻게 해야할지 모르겠습니다.
트리노드 부분을 어떻게 변경해야 하나요,,?

**Comment by likejazz** [comment]
트리 형태로 입력해주셔야 합니다. 상단에 보면 이미 `TreeNode` 클래스도 선언되어 있기 때문에 저대로 형식에 맞춰 입력해주면 됩니다.

```
root1 = TreeNode(1)
root1.left = TreeNode(3)
root1.left.left = TreeNode(5)
root1.right = TreeNode(2)

root2 = TreeNode(2)
root2.left = TreeNode(1)
root2.left.right = TreeNode(4)
root2.right = TreeNode(3)
root2.right.right = TreeNode(7)

sol = Solution()
check = sol.mergeTrees(root1, root2)
```

이렇게 해서 `check`의 값을 하나씩 조회해보시면 원하는 형태로 합병되어 있음을 확인할 수 있습니다.
